job:
  package-manager: npm_and_yarn
  allowed-updates:
    - update-type: all
  dependency-groups:
    - name: npm
      rules:
        patterns:
          - "*"
  source:
    directory: /
    provider: github
    repo: vdaas/vald-client-node
